### PR TITLE
Basic 400 level alerting and application errors

### LINKED ISSUE #74: SRV-H-2.1: Alarms
**Finding**:
Deployment lacks alarming

**Recommendation**: 
Appropriate thresholds should be placed on KPIs for alarming

### LINKED ISSUE #97: VA78 - HealthCare API Key Alarm
401 on OTC API Key failure - at a certain threshold should trigger alarm / alert through existing alerting streams

Decision Needed: what is the appropriate threshold
Note: IP address should not be factor to protect from those who use IP hopping

_This came from the vulnerability analysis; originally Loudmouth Recommendation 2 but re-solutioned to make sense for application_

### PR DESCRIPTION
**Pull request by maxneuvians**
Closes #74 and closes #97 
Adds the following alerts for #74:

- Threshold for unauthorized responses to `/new-key-claim`
- Threshold for unauthorized responses to `/claim-key`
- Threshold for 400 level responses to `/upload`
- Threshold for 500 level responses
- Threshold for `level=error` logs
- Threshold for `level=fatal` logs

### CODE REVIEW

**Comment by whytoe** [comment]
This looks great, I created my Alarms under `cloudwatch.tf` as there was already alarms put there previously.

**Comment by maxneuvians** [comment]
I though about splitting the files, but I think we can merge them as you suggested

**Comment by whytoe** [comment]
Does this resolve #97 as well?

**Comment by maxneuvians** [comment]
No the alerts from #97 are app specific and need to be pulled out of the JSON metrics blobs - CloudWatch has a very ugly way of doing this.

**Pull request merged**
